{
 "title": "Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nombre de coeurs",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count\")"
      }
     ]
    },
    {
     "title": "Nombre de coeurs physiques",
     "type": "stat",
     "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"count_physical\")"
      }
     ]
    },
    {
     "title": "Utilisation CPU pour chaque coeurs",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 16, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"percent_of_use_0\")"
      },
      {
       "query": "from(bucket: \"metrics\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"percent_of_use_1\")"
      },
      {
       "query": "from(bucket: \"metrics\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"percent_of_use_2\")"
      },
      {
       "query": "from(bucket: \"metrics\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"percent_of_use_3\")"
      },
      {
       "query": "from(bucket: \"metrics\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"percent_of_use_4\")"
      },
      {
       "query": "from(bucket: \"metrics\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"percent_of_use_5\")"
      },
      {
       "query": "from(bucket: \"metrics\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"percent_of_use_6\")"
      },
      {
       "query": "from(bucket: \"metrics\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"percent_of_use_7\")"
      }
     ]
    },
    {
     "title": "Utilisation CPU",
     "type": "stat",
     "gridPos": { "h": 9, "w": 3, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"percent_of_use\")"
      }
     ]
    },
    {
     "title": "Utilisation CPU",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 21, "x": 3, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"cpu\")\n  |> filter(fn: (r) => r[\"_field\"] == \"percent_of_use\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Espace total",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"disk_storage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"total\")"
      }
     ]
    },
    {
     "title": "Espace libre",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"disk_storage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"free\")"
      }
     ]
    },
    {
     "title": "Espace utilisé",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"disk_storage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used\")"
      }
     ]
    },
    {
     "title": "Espace utilisé",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"disk_storage\")\n  |> filter(fn: (r) => r[\"_field\"] == \"percent\")"
      }
     ]
    }
   ]
  },
  { "title": "Capteurs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Pourcentage batterie",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"sensors\")\n  |> filter(fn: (r) => r[\"_field\"] == \"percent\")"
    }
   ]
  },
  {
   "title": "Temps restant batterie",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"metrics\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"sensors\")\n  |> filter(fn: (r) => r[\"_field\"] == \"secsleft\")"
    }
   ]
  },
  {
   "title": "Réseau",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Montant",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"network\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_sent\")"
      }
     ]
    },
    {
     "title": "Descendant",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"network\")\n  |> filter(fn: (r) => r[\"_field\"] == \"bytes_recv\")"
      }
     ]
    },
    {
     "title": "Paquets envoyés",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"network\")\n  |> filter(fn: (r) => r[\"_field\"] == \"packets_sent\")"
      }
     ]
    },
    {
     "title": "paquets reçus",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n\t|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"network\")\n  |> filter(fn: (r) => r[\"_field\"] == \"packets_recv\")"
      }
     ]
    }
   ]
  },
  {
   "title": "Mémoire",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mémoire virtuelle",
     "type": "stat",
     "description": "Mémoire physique totale, à l'exclusion de l'espace d'échange",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"memory\")\n  |> filter(fn: (r) => r[\"_field\"] == \"virtual_total\")"
      }
     ]
    },
    {
     "title": "Mémoire virtuelle",
     "type": "stat",
     "description": "mémoire non utilisée (mise à zéro) et facilement disponible",
     "gridPos": { "h": 5, "w": 5, "x": 6, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"memory\")\n  |> filter(fn: (r) => r[\"_field\"] == \"virtual_free\")"
      }
     ]
    },
    {
     "title": "Mémoire virtuelle",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 13, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"memory\")\n  |> filter(fn: (r) => r[\"_field\"] == \"virtual_used\")"
      }
     ]
    },
    {
     "title": "Mémoire virtuelle",
     "type": "stat",
     "description": "la mémoire qui peut être donnée instantanément aux processus sans que le système n'entre en swap",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"memory\")\n  |> filter(fn: (r) => r[\"_field\"] == \"virtual_available\")"
      }
     ]
    },
    {
     "title": "Mémoire virtuelle",
     "type": "stat",
     "description": "mémoire actuellement utilisée ou très récemment utilisée",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"memory\")\n  |> filter(fn: (r) => r[\"_field\"] == \"virtual_active\")"
      }
     ]
    },
    {
     "title": "Mémoire virtuelle",
     "type": "stat",
     "description": "la mémoire qui est marquée comme non utilisée",
     "gridPos": { "h": 5, "w": 5, "x": 6, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"memory\")\n  |> filter(fn: (r) => r[\"_field\"] == \"virtual_inactive\")"
      }
     ]
    },
    {
     "title": "Mémoire virtuelle",
     "type": "stat",
     "description": "la mémoire qui est marquée pour rester toujours dans la RAM. Elle n'est jamais déplacée sur le disque",
     "gridPos": { "h": 5, "w": 5, "x": 13, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"memory\")\n  |> filter(fn: (r) => r[\"_field\"] == \"virtual_wired\")"
      }
     ]
    },
    {
     "title": "Mémoire virtuelle",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"memory\")\n  |> filter(fn: (r) => r[\"_field\"] == \"virtual_percent\")"
      }
     ]
    },
    {
     "title": "Mémoire swap",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"memory\")\n  |> filter(fn: (r) => r[\"_field\"] == \"swap_total\")"
      }
     ]
    },
    {
     "title": "Mémoire swap",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 6, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"memory\")\n  |> filter(fn: (r) => r[\"_field\"] == \"swap_used\")"
      }
     ]
    },
    {
     "title": "Mémoire swap",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 13, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"memory\")\n  |> filter(fn: (r) => r[\"_field\"] == \"swap_free\")"
      }
     ]
    },
    {
     "title": "Mémoire swap",
     "type": "gauge",
     "description": "le pourcentage d'utilisation qui est calculé comme (total - disponible) / total * 100",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"memory\")\n  |> filter(fn: (r) => r[\"_field\"] == \"swap_percent\")"
      }
     ]
    },
    {
     "title": "Mémoire swap",
     "type": "stat",
     "description": "le nombre de bytes que le système a échangé depuis le disque",
     "gridPos": { "h": 5, "w": 5, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"memory\")\n  |> filter(fn: (r) => r[\"_field\"] == \"swap_sin\")"
      }
     ]
    },
    {
     "title": "Mémoire swap",
     "type": "stat",
     "description": "le nombre de bytes que le système a retiré du disque",
     "gridPos": { "h": 5, "w": 5, "x": 6, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "from(bucket: \"metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"tag\"] == \"memory\")\n  |> filter(fn: (r) => r[\"_field\"] == \"swap_sout\")"
      }
     ]
    }
   ]
  }
 ]
}